In [1]:
# ** What is 7 to the power of 4?**
y=7**4
y

2401

In [5]:
# ** Split this string:**

# s = "Hi there Sam!"
# *into a list. *
s='Hi there Sam'
m=s.split()
m

['Hi', 'there', 'Sam']

In [11]:
tweet= "Hi there Dad"
tweet.split()

['Hi', 'there', 'Dad']

In [6]:
# ** Given the variables:**

# planet = "Earth"
# diameter = 12742
# ** Use .format() to print the following string: **

# The diameter of Earth is 12742 kilometers.
planet = "Earth"
diameter = 12742

In [8]:
print("The diameter of the {} is {} kilometers".format(planet,diameter))

The diameter of the Earth is 12742 kilometers


In [2]:
# ** Given this nested list, use indexing to grab the word "hello" **
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [5]:
lst.count(1)

2

In [18]:
lst[3][1][2][0]

'hello'

In [19]:
# ** Given this nested dictionary grab the word "hello". Be prepared, this will be annoying/tricky **
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [29]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [5]:
# ** Create a function that grabs the email website domain from a string in the form: **

# user@domain.com
# So for example, passing "user@domain.com" would return: domain.com
def getDomain(email):
    m=email.split('@')
    return(m)[1]
    

In [9]:
getDomain('elgizzy7@yahoo.com')

'yahoo.com'

In [10]:
# ** Create a basic function that returns True if the word 'dog' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization. **
def checkDog(params):
    if "dog" in params:
        print(True)
    else:
         print(False)
        


In [13]:
checkDog("he's dog")

True


In [7]:
# ** Create a function that counts the number of times the word "dog" occurs in a string. Again ignore edge cases. **
def checkDog(params):
    n=params.split()
    return n.count('dog')
 

In [8]:
checkDog('the dog  dog dog is playing with the other dog')

4

In [264]:
# ** Use lambda expressions and the filter() function to filter out words from a list that don't start with the letter 's'. For example:**

# seq = ['soup','dog','salad','cat','great']
# should be filtered down to:

# ['soup','salad']
seq = ['soup','dog','salad','cat','great']

In [310]:
[i for i in filter(lambda y: y.startswith("s"),seq)]

['soup', 'salad']

In [311]:
m =8
def paul(v):
    return v
nm= paul(m)

In [312]:
nm

8

In [313]:
m=4
b=lambda m:m+nm
b(m)

12

In [314]:
lol= lambda ll:ll**2
lol(8)

64

In [66]:
# *You are driving a little too fast, and a police officer stops you. 
# Write a function to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
# If your speed is 60 or less, the result is "No Ticket".
# If speed is between 61 and 80 inclusive, the result is "Small Ticket". 
# If speed is 81 or more, the result is "Big Ticket". 
# Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases. *
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    if speeding<=61:
        return 'No Ticket'
    elif (speeding >=61 and speeding<=81):
        return 'Small Ticket'
    else:
        return 'Big Ticket'
    

In [67]:
caught_speeding(82,True)

'Small Ticket'

In [68]:
caught_speeding(82,False)

'Big Ticket'

In [99]:
shape=['Underweight','Normal','Overweight','Obese']
for x in shape:
    print(x)

Underweight
Normal
Overweight
Obese


In [10]:
# calculate BMI
shape=['Underweight','Normal','Overweight','Obese']
# for x in shape:
#     print(x)
weight= int(input())  
height= float(input())            
val=height**2
_bmi=weight/val
if _bmi < 18.5:
    x =shape[0]
elif _bmi > 18.5 and _bmi < 20.5:
    x =shape[1]
elif _bmi > 20.5 and _bmi < 25:
    x =shape[2]
else:
    x=shape[3]
print("Your BMI is {} and you are considered {}".format(_bmi,x))

67
1.45
Your BMI is 31.86682520808561 and you are considered Obese


In [13]:
import copy

In [14]:
s=[7,8,9,0,6,4]

In [17]:
t=copy.deepcopy(s)
t

[7, 8, 9, 0, 6, 4]

In [2]:
import numpy as np
import pandas as pd
import twint
import nest_asyncio


C:\Users\User\anaconda3\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


twitter scraping


In [3]:
config=twint.Config()
config.Username='True_Jude'
config.Search='Van dijk'
config.Lang='en'
config.Since="2021-04-03"
config.Until="2022-03-01"
nest_asyncio.apply()
twint.run.Search(config)
# config.Limit=100

# config.Store_json=True
# config.Output="custom_out.json"
# twint.run.Search(config)

CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 8.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 27.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 64.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 125.0 secs


KeyboardInterrupt: 

Youtube Scraping

In [149]:
from pytube import YouTube

In [150]:
link=input('Type in the Youtube link')
yt=YouTube(link)

Type in the Youtube linkhttps://youtu.be/MsdyvI3ZI5k


In [151]:
# to get the title
print("Title :", yt.title)
# To get number of views
print("Views :", yt.views)
# To get the length of video
print("Duration :", yt.length)
# To get description
print("Description :", yt.description)
# To get ratings
print("Ratings : ", yt.rating)

Title : Data Science Salaries in Amsterdam: Talking about Money 🤑, Benefits & Dutch Working Culture
Views : 1295
Duration : 848
Description : 👩🏻‍💻 My laptop and iPad for doing DS/ study 👉 https://kit.co/thuvu/computer-ipad
⚙️ Tech I use for making Youtube videos 👉 https://kit.co/thuvu/my-budget-youtube-gear
🔍Check out my other videos on Data Analyst/ Data Science 👉 https://bit.ly/3qW9YpU

🇳🇱Tax calculation in the Netherlands: https://bit.ly/34PJ1fa

Hello everyone! In today's video, I'll be talking about the data science job landscape in Amsterdam, the Netherlands: salaries of different data science jobs, benefits, and the Dutch working culture. I have lived and worked in the Netherlands for more than 6 years. I took a Master's in Amsterdam, graduated, got an internship, and fast forward I have had 2 full-time data science jobs since. This video is requested by one of my subscribers, and I had a lot of fun making it! Hope you enjoyed this video and thank you for watching! 👋

COURSES & 

In [152]:
yam=yt.streams.get_highest_resolution()
yam.download()
print('Download completed')

Download completed


In [4]:
import numpy as np
import pandas as pd

In [5]:
n=np.arange(51)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [6]:
df=pd.DataFrame(n)
df.head()

0
0  0
1  1
2  2
3  3
4  4

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [132]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
np.random.rand(1)

array([0.45546244])

In [136]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [140]:
np.random.randn(25)

array([ 1.55966159,  1.04839176, -0.22685961, -0.6864239 ,  1.25231039,
       -0.28346399, -2.15040255,  1.34987072,  1.96074067, -0.42761178,
       -0.02357428, -0.66035854, -1.34848753,  0.37115692, -1.09337287,
       -0.38159458,  0.55553393, -0.3265508 ,  0.06637842, -0.06406271,
        2.16813288, -0.69709589,  0.73416605,  0.72916153, -0.0933729 ])

In [143]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [73]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [79]:
mat[3,4]

20

In [144]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [85]:
mat[4]

array([21, 22, 23, 24, 25])

In [86]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
mat.sum()

325

In [88]:
mat.std()

7.211102550927978

In [106]:
mat[0,1:].sum()

14

In [130]:
a=mat[0:,0:1]
b=mat[0:,1:2]
c=mat[0:,2:3]
d=mat[0:,3:4]
e=mat[0:,4:]


In [131]:
np.array([a.sum(),b.sum(),c.sum(),d.sum(),e.sum()])

array([55, 60, 65, 70, 75])

In [147]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [220]:
sal=pd.read_csv('C:\\Users\\User\\Downloads\\Python-Data-Science-and-Machine-Learning-Bootcamp\\Python-for-Data-Analysis\\Pandas\\Pandas Exercises\\Salaries.csv')
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [191]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [192]:
sal['BasePay'].mean()

66325.44884050643

In [193]:
 sal['OvertimePay'].max()

245131.88

In [197]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [278]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [204]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [205]:
sal.iloc[sal['TotalPayBenefits'].argmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                     167411
OvertimePay                                                      0
OtherPay                                                    400184
Benefits                                                       NaN
TotalPay                                                    567595
TotalPayBenefits                                            567595
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [206]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [207]:
sal.iloc[sal['TotalPayBenefits'].argmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                      0
OvertimePay                                  0
OtherPay                               -618.13
Benefits                                     0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

In [283]:
sal.groupby('Year').mean()['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [241]:
print(len(sal['JobTitle'].value_counts()))

2159


In [290]:
sal['JobTitle'].nunique()

2159

In [249]:
m=sal['JobTitle'].value_counts()
m

Transit Operator                                      7036
Special Nurse                                         4389
Registered Nurse                                      3736
Public Svc Aide-Public Works                          2518
Police Officer 3                                      2421
                                                      ... 
FEASIBILITY ANALYST, PORT                                1
CHIEF MICROBIOLOGIST                                     1
ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS       1
DIRECTOR, JUVENILE HALL                                  1
ELECTRIC MOTOR REPAIR SUPERVISOR I                       1
Name: JobTitle, Length: 2159, dtype: int64

In [251]:
m.head(5)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [289]:
sal['Year']==2013

0         False
1         False
2         False
3         False
4         False
          ...  
148649    False
148650    False
148651    False
148652    False
148653    False
Name: Year, Length: 148654, dtype: bool