In [1]:
instructions= """Instruction
If you input 1, it represents addition ('+')
If you input 1, it represents addition ("*")
If you input 1, it represents addition ('-')
If you input 1, it represents addition ('/')
"""
print(instructions)
fn=float(input("enter a number"))
sn=float(input("enter a second number"))
on=input("enter the operator number 1,2,3 or 4")

if on == "1":
    print(fn+sn)
elif on == "2":
    print(fn*sn)
elif on == "3":
    print(fn-sn)
elif on == "4":
    print(fn/sn)
else:
    print("invalid command")

Instruction
If you input 1, it represents addition ('+')
If you input 1, it represents addition ("*")
If you input 1, it represents addition ('-')
If you input 1, it represents addition ('/')

enter a number6
enter a second number7
enter the operator number 1,2,3 or 42
42.0


In [2]:
import numpy as np
import pandas as pd

In [3]:
# create series array
num = pd.Series([1, 2, 3, 4, 5, 6, 7, 8])
num

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [4]:
# to see only the values of the series
num.values

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [5]:
# to see only the index of the series
num.index

RangeIndex(start=0, stop=8, step=1)

In [6]:
# we can get each element of series by index
num[3]

4

In [7]:
# we can also perform slice on a series object
num[3:6]

3    4
4    5
5    6
dtype: int64

In [8]:
# we can also perform slice on a series object
num[3:]

3    4
4    5
5    6
6    7
7    8
dtype: int64

In [9]:
#slicing from the series using the negative index
num[-5:-1]

3    4
4    5
5    6
6    7
dtype: int64

In [10]:
# To slice from a particular index to the end using negative index
num[-9:]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [11]:
# To slice from a particular index to the end using negative index
num[-7:]

1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [12]:
#specifying your index 
num2 = pd.Series([10, 11, 12, 13, 14, 15, 16, 17, 18,19,20], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i','j','k'])
num2

a    10
b    11
c    12
d    13
e    14
f    15
g    16
h    17
i    18
j    19
k    20
dtype: int64

In [13]:
# selecting items from the series using the specified index
num2['d']

13

In [14]:
#selection from the series using slice indexing
num2['c':]

c    12
d    13
e    14
f    15
g    16
h    17
i    18
j    19
k    20
dtype: int64

In [15]:
#using noncontiguous or nonsequential indeces
num3 = pd.Series([20,21,22,23,24,25,26,27,28], index=[5,3,6,1,7,4,2,7,9])
num3

5    20
3    21
6    22
1    23
7    24
4    25
2    26
7    27
9    28
dtype: int64

In [16]:
# accessing series item by its index
num3[7]

7    24
7    27
dtype: int64

In [17]:
num3[9]

28

# Different Ways Of Creating Series Object

In [18]:
# from a specialized dictionary
states = {'Oyo':2500000, 'Lagos':6400000, 'Kano':4600000, 'Kaduna':3600000, 'Enugu':3400000, 'Imo':2300000,"Benue":600000}
statesdata = pd.Series(states)
statesdata

Oyo       2500000
Lagos     6400000
Kano      4600000
Kaduna    3600000
Enugu     3400000
Imo       2300000
Benue      600000
dtype: int64

In [19]:
# the data can be indexed using the state name
statesdata['Kano']

4600000

In [20]:
# we can also perform slicing on the data
statesdata['Oyo':'Kaduna']

Oyo       2500000
Lagos     6400000
Kano      4600000
Kaduna    3600000
dtype: int64

## Constructing Series Object

In [21]:
# series can be created through a scalar data
values = pd.Series(1000, index=[1,2,3,4,5,6,7,6])
values

1    1000
2    1000
3    1000
4    1000
5    1000
6    1000
7    1000
6    1000
dtype: int64

In [22]:
# index can be explicitly set if different result is prefered
valuekey = pd.Series({1:'Oyo', 2:'Lagos', 3:'Abuja', 4:'Enugu', 5:'Rivers'}, index=['O', 'L', 'A','E','R'])
valuekey

O    NaN
L    NaN
A    NaN
E    NaN
R    NaN
dtype: object

In [23]:
landmass = {'Oyo':5000, 'Lagos':2000, 'Kano':7000, 'Kaduna':3000, 'Enugu':4000,'Imo':1500}
landmasses= pd.Series(landmass)
landmasses

Oyo       5000
Lagos     2000
Kano      7000
Kaduna    3000
Enugu     4000
Imo       1500
dtype: int64

# Creating A Dataframe Object

In [24]:
# creating dataframe from single dictionary
census = pd.DataFrame({'Population':statesdata})
census

Population
Oyo        2500000
Lagos      6400000
Kano       4600000
Kaduna     3600000
Enugu      3400000
Imo        2300000
Benue       600000

In [25]:
# creating dataframe from multiple dictionaries
pop_census = pd.DataFrame({'Population':statesdata, 'LandMass':landmasses})
pop_census

Population  LandMass
Benue       600000       NaN
Enugu      3400000    4000.0
Imo        2300000    1500.0
Kaduna     3600000    3000.0
Kano       4600000    7000.0
Lagos      6400000    2000.0
Oyo        2500000    5000.0

In [26]:
# creating dataframe with some missing values
land = pd.Series({'Rivers':5000, 'Lagos':2000, 'Edo':7000, 'Kaduna':3000, 'Benue':4000, 'Imo':1500})
census = pd.DataFrame({'Population':statesdata, 'LandMass':land})
census

Population  LandMass
Benue     600000.0    4000.0
Edo            NaN    7000.0
Enugu    3400000.0       NaN
Imo      2300000.0    1500.0
Kaduna   3600000.0    3000.0
Kano     4600000.0       NaN
Lagos    6400000.0    2000.0
Oyo      2500000.0       NaN
Rivers         NaN    5000.0

In [27]:
# list out the index 
census.index

Index(['Benue', 'Edo', 'Enugu', 'Imo', 'Kaduna', 'Kano', 'Lagos', 'Oyo',
       'Rivers'],
      dtype='object')

In [28]:
# list out the index 
pop_census.index

Index(['Benue', 'Enugu', 'Imo', 'Kaduna', 'Kano', 'Lagos', 'Oyo'], dtype='object')

In [29]:
# list out the columns on the table
pop_census.columns

Index(['Population', 'LandMass'], dtype='object')

In [30]:
# list out all the values of the dataframe
census.values

array([[6.0e+05, 4.0e+03],
       [    nan, 7.0e+03],
       [3.4e+06,     nan],
       [2.3e+06, 1.5e+03],
       [3.6e+06, 3.0e+03],
       [4.6e+06,     nan],
       [6.4e+06, 2.0e+03],
       [2.5e+06,     nan],
       [    nan, 5.0e+03]])

In [31]:
# indexing a dataframe through it column name
census['Population']

Benue      600000.0
Edo             NaN
Enugu     3400000.0
Imo       2300000.0
Kaduna    3600000.0
Kano      4600000.0
Lagos     6400000.0
Oyo       2500000.0
Rivers          NaN
Name: Population, dtype: float64

In [32]:
# get the landmass of Lagos using the column name and index name
census['LandMass']['Enugu']

nan

In [33]:
# get the landmass of Lagos using the column name and index name
pop_census['Population']['Lagos']

6400000

In [34]:
# slicing the dataframe using indexing
census['Benue':'Kaduna']

Population  LandMass
Benue     600000.0    4000.0
Edo            NaN    7000.0
Enugu    3400000.0       NaN
Imo      2300000.0    1500.0
Kaduna   3600000.0    3000.0

In [35]:
# give us the complete details of Kaduna state
census['Kaduna':'Kaduna']

Population  LandMass
Kaduna   3600000.0    3000.0

# Constructing Dataframe Object

In [36]:
#creating dataframe from a single series object
student = pd.Series(['Sunday', 'Sayo', 'Charse', 'Rose', 'Michael'])
student

0     Sunday
1       Sayo
2     Charse
3       Rose
4    Michael
dtype: object

In [37]:
# convert the series to dataframe specifying the column name and setting new index
studentrec= pd.DataFrame(student, columns=['Student Name'], index=[0,1,2,3,4])
studentrec

Student Name
0       Sunday
1         Sayo
2       Charse
3         Rose
4      Michael

In [38]:
stud= pd.DataFrame({"Student Name":student})
stud

Student Name
0       Sunday
1         Sayo
2       Charse
3         Rose
4      Michael

In [39]:
# Dataframe from multidimension numpy array
studentpop = pd.DataFrame(np.random.rand(4,3), columns=['Male', "Female","Hermaphrodite"], index=['Js1', 'Js2', 'Js3','Ss1'])
studentpop

Male    Female  Hermaphrodite
Js1  0.537974  0.852350       0.663431
Js2  0.558614  0.562204       0.508210
Js3  0.700387  0.266937       0.150398
Ss1  0.319947  0.041504       0.919090

In [40]:
# return the values of the studentpop
newVal = studentpop.values
newVal

array([[0.53797415, 0.85235012, 0.66343108],
       [0.55861438, 0.56220424, 0.50820973],
       [0.70038732, 0.26693731, 0.15039761],
       [0.31994668, 0.04150393, 0.91908977]])

In [41]:
# we can inverse between index and column
studentpop.T

Js1       Js2       Js3       Ss1
Male           0.537974  0.558614  0.700387  0.319947
Female         0.852350  0.562204  0.266937  0.041504
Hermaphrodite  0.663431  0.508210  0.150398  0.919090

# Pandas Object

In [42]:
# example of index in numpy array
list1 = np.array([1,2,3,4,5,6,7,8,9])
list1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# using fancy indexing
fancy = [0,3,6,8]
list1[fancy]

array([1, 4, 7, 9])

In [44]:
# creating index object in pandas
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [45]:
# index as immutable array
ind[-1]

11

In [46]:
# index object can also be sliced
ind[::3]

Int64Index([2, 7], dtype='int64')

In [47]:
# index object also have the same numpy attributs
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [48]:
# index object as immutable  array cannot be modified
ind[2] = 10

TypeError: Index does not support mutable operations

In [49]:
# index can be used to perform set operations
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 9,11])

In [50]:
# intersection
# indA & indB (the use of & operator for intersection between two index object is deprecated)
indA.intersection(indB)

Int64Index([3, 5, 7, 9], dtype='int64')

In [51]:
# union
# indA | indB (the use of | operator for intersection between two index object is deprecated)
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [52]:
# symmetric difference
# indA ^ indB (the use of ^ operator for intersection between two index object is deprecated)
indA.symmetric_difference(indB)

Int64Index([1, 2, 11], dtype='int64')

# Data Indexing and Selection

In [53]:
# Data selection in Series
# Series as dictionary
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [54]:
# selecting using index
data['d']

1.0

In [55]:
# We can use dictionary-like python expression and methods to check for key/indices and values
#check for index
'c' in data

True

In [56]:
# check for key
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [57]:
# check for values
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [58]:
# check for both key/indices and values
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [59]:
# Series object can be modified just like dictionary using dictionary-like sytax
# adding new value to series
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [60]:
# Series object can be modified just like dictionary using dictionary-like sytax
# adding new value to series
data['g'] = 1.35
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
g    1.35
dtype: float64

In [61]:
# Series as one-demensional array
# slicing by explicit index
data['a':'d']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [62]:
# slicing by explicit integer index
data[0:5]

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [63]:
# masking 
data[(data>0.3) & (data<1.5)]

b    0.50
c    0.75
d    1.00
e    1.25
g    1.35
dtype: float64

In [64]:
# fancy indexig
data[['a', 'c', 'g']]

a    0.25
c    0.75
g    1.35
dtype: float64

In [65]:
# slicing with loc, iloc and ix
data.loc['g']

1.35

In [66]:
data.iloc[3]

1.0

In [67]:
# Data Selection in DataFrame
# DataFrame as dictionary
pop_census

Population  LandMass
Benue       600000       NaN
Enugu      3400000    4000.0
Imo        2300000    1500.0
Kaduna     3600000    3000.0
Kano       4600000    7000.0
Lagos      6400000    2000.0
Oyo        2500000    5000.0

In [68]:
# select based on column names
pop_census['Population']

Benue      600000
Enugu     3400000
Imo       2300000
Kaduna    3600000
Kano      4600000
Lagos     6400000
Oyo       2500000
Name: Population, dtype: int64

In [69]:
# select based on column names
pop_census['LandMass']

Benue        NaN
Enugu     4000.0
Imo       1500.0
Kaduna    3000.0
Kano      7000.0
Lagos     2000.0
Oyo       5000.0
Name: LandMass, dtype: float64

In [70]:
# we can also selection using the column name as an attribute-style 
pop_census.Population

Benue      600000
Enugu     3400000
Imo       2300000
Kaduna    3600000
Kano      4600000
Lagos     6400000
Oyo       2500000
Name: Population, dtype: int64

In [71]:
# compare if the two methods are equal
pop_census.Population is pop_census['Population']

True

In [72]:
# we can modify the values of dataframe like adding new columns
pop_census['Density']=pop_census['Population'] / pop_census.LandMass
pop_census

Population  LandMass      Density
Benue       600000       NaN          NaN
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000
Kano       4600000    7000.0   657.142857
Lagos      6400000    2000.0  3200.000000
Oyo        2500000    5000.0   500.000000

In [73]:
# Return the values of the DataFrame as two dimensional arry
pop_census.values

array([[6.00000000e+05,            nan,            nan],
       [3.40000000e+06, 4.00000000e+03, 8.50000000e+02],
       [2.30000000e+06, 1.50000000e+03, 1.53333333e+03],
       [3.60000000e+06, 3.00000000e+03, 1.20000000e+03],
       [4.60000000e+06, 7.00000000e+03, 6.57142857e+02],
       [6.40000000e+06, 2.00000000e+03, 3.20000000e+03],
       [2.50000000e+06, 5.00000000e+03, 5.00000000e+02]])

In [74]:
# Returns the index of the DataFrame as a vector
pop_census.index

Index(['Benue', 'Enugu', 'Imo', 'Kaduna', 'Kano', 'Lagos', 'Oyo'], dtype='object')

In [75]:
pop_census.T

Benue      Enugu           Imo     Kaduna          Kano  \
Population  600000.0  3400000.0  2.300000e+06  3600000.0  4.600000e+06   
LandMass         NaN     4000.0  1.500000e+03     3000.0  7.000000e+03   
Density          NaN      850.0  1.533333e+03     1200.0  6.571429e+02   

                Lagos        Oyo  
Population  6400000.0  2500000.0  
LandMass       2000.0     5000.0  
Density        3200.0      500.0

In [76]:
# indexing a dataframe object
pop_census.values[2]

array([2.30000000e+06, 1.50000000e+03, 1.53333333e+03])

In [77]:
# indexing using the column name
pop_census['LandMass']

Benue        NaN
Enugu     4000.0
Imo       1500.0
Kaduna    3000.0
Kano      7000.0
Lagos     2000.0
Oyo       5000.0
Name: LandMass, dtype: float64

In [78]:
# using loc, iloc and ix
# use iloc with explicit integer index
pop_census.iloc[:5, :3]

Population  LandMass      Density
Benue       600000       NaN          NaN
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000
Kano       4600000    7000.0   657.142857

In [79]:
# use loc for explicit index name
pop_census.loc['Benue':'Oyo']

Population  LandMass      Density
Benue       600000       NaN          NaN
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000
Kano       4600000    7000.0   657.142857
Lagos      6400000    2000.0  3200.000000
Oyo        2500000    5000.0   500.000000

In [80]:
# using ix as an hybrid of loc and iloc
# pop_census.ix[:3, :'Population'] #this is already deprecated in the new version of pandas 
# so use this method 
pop_census.iloc[:5]['LandMass']

Benue        NaN
Enugu     4000.0
Imo       1500.0
Kaduna    3000.0
Kano      7000.0
Name: LandMass, dtype: float64

In [81]:
studentpop

Male    Female  Hermaphrodite
Js1  0.537974  0.852350       0.663431
Js2  0.558614  0.562204       0.508210
Js3  0.700387  0.266937       0.150398
Ss1  0.319947  0.041504       0.919090

In [82]:
# loc can be combine with masking and fancy indexing 
studentpop.loc[studentpop['Hermaphrodite']  >0.356, ['Male','Female']]

Male    Female
Js1  0.537974  0.852350
Js2  0.558614  0.562204
Ss1  0.319947  0.041504

In [83]:
pop_census.loc[pop_census.Density > 800, ['LandMass','Population']]

LandMass  Population
Enugu     4000.0     3400000
Imo       1500.0     2300000
Kaduna    3000.0     3600000
Lagos     2000.0     6400000

In [84]:
# Any of this method can be used to modify the values
pop_census.iloc[0, 2] = 50000
pop_census

Population  LandMass       Density
Benue       600000       NaN  50000.000000
Enugu      3400000    4000.0    850.000000
Imo        2300000    1500.0   1533.333333
Kaduna     3600000    3000.0   1200.000000
Kano       4600000    7000.0    657.142857
Lagos      6400000    2000.0   3200.000000
Oyo        2500000    5000.0    500.000000

In [85]:
# Any of this method can be used to modify the values
pop_census.iloc[0, 1] = 50000
pop_census

Population  LandMass       Density
Benue       600000   50000.0  50000.000000
Enugu      3400000    4000.0    850.000000
Imo        2300000    1500.0   1533.333333
Kaduna     3600000    3000.0   1200.000000
Kano       4600000    7000.0    657.142857
Lagos      6400000    2000.0   3200.000000
Oyo        2500000    5000.0    500.000000

In [86]:
# we can modify the values of dataframe like adding new columns
pop_census['Density']=pop_census['Population'] / pop_census.LandMass
pop_census

Population  LandMass      Density
Benue       600000   50000.0    12.000000
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000
Kano       4600000    7000.0   657.142857
Lagos      6400000    2000.0  3200.000000
Oyo        2500000    5000.0   500.000000

In [87]:
# slicing using the rows
pop_census['Enugu':'Lagos']

Population  LandMass      Density
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000
Kano       4600000    7000.0   657.142857
Lagos      6400000    2000.0  3200.000000

In [88]:
# slicing using row integer index
pop_census[1:4]

Population  LandMass      Density
Enugu      3400000    4000.0   850.000000
Imo        2300000    1500.0  1533.333333
Kaduna     3600000    3000.0  1200.000000

In [89]:
# Direct masking can also be done row-wise instead of column-wise
pop_census[pop_census.Density > 1200.000000]

Population  LandMass      Density
Imo       2300000    1500.0  1533.333333
Lagos     6400000    2000.0  3200.000000

# ufuncs in Pandas

In [90]:
# create a series object
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 6))
ser

0    6
1    3
2    7
3    4
4    6
5    9
dtype: int32

In [91]:
# creat a dataframe object
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  2  6  7  4
1  3  7  7  2
2  5  4  1  7

In [92]:
# perform an exponential ufunc on the series 
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
4     403.428793
5    8103.083928
dtype: float64

In [93]:
# we can also perform more complex operation by combining multiple ufunc together
np.sin(df * np.pi/4)

A             B         C             D
0  1.000000 -1.000000e+00 -0.707107  1.224647e-16
1  0.707107 -7.071068e-01 -0.707107  1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01

In [94]:
# we can apply the same ufunc on our pop_census data
np.sin(pop_census * np.pi/4)

Population      LandMass       Density
Benue  -2.183715e-11 -4.245082e-12  3.673940e-16
Enugu  -2.673108e-11 -3.214166e-13  1.000000e+00
Imo     2.300497e-11  6.368782e-14 -8.660254e-01
Kaduna -2.474382e-10 -1.273756e-13 -5.095026e-14
Kano    4.600994e-11 -4.487923e-13  7.818315e-01
Lagos  -5.433705e-10 -1.607083e-13  1.571509e-14
Oyo     3.512847e-11 -6.071029e-14  4.017708e-14

In [98]:
# let us try to practice with a real dataset using california city data
data = pd.read_csv('C:\\Users\\User\\Desktop\\Datasets\\california_cities.csv')
data.head()

Unnamed: 0         city       latd       longd  elevation_m  elevation_ft  \
0           0     Adelanto  34.576111 -117.432778        875.0        2871.0   
1           1  AgouraHills  34.153333 -118.761667        281.0         922.0   
2           2      Alameda  37.756111 -122.274444          NaN          33.0   
3           3       Albany  37.886944 -122.297778          NaN          43.0   
4           4     Alhambra  34.081944 -118.135000        150.0         492.0   

   population_total  area_total_sq_mi  area_land_sq_mi  area_water_sq_mi  \
0             31765            56.027           56.009             0.018   
1             20330             7.822            7.793             0.029   
2             75467            22.960           10.611            12.349   
3             18969             5.465            1.788             3.677   
4             83089             7.632            7.631             0.001   

   area_total_km2  area_land_km2  area_water_km2  area_water_percent  \
0         145.107        145.062           0.046                0.03   
1          20.260         20.184           0.076                0.37   
2          59.465         27.482          31.983               53.79   
3          14.155          4.632           9.524               67.28   
4          19.766         19.763           0.003                0.01   

   Unnamed: 14  Unnamed: 15  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN

In [99]:
# Let us describe the data to see general overview of the whole dataset
data.describe()

Unnamed: 0        latd       longd  elevation_m  elevation_ft  \
count  482.000000  482.000000  482.000000   434.000000    470.000000   
mean   240.500000   36.095088 -119.837714   180.416705    567.168723   
std    139.285678    2.298006    2.147676   309.531825   1001.265722   
min      0.000000   32.578333 -124.263333   -34.000000   -180.000000   
25%    120.250000   33.977292 -121.954931    22.000000     69.000000   
50%    240.500000   36.204722 -119.708611    67.000000    200.000000   
75%    360.750000   37.886667 -117.977292   173.500000    515.000000   
max    481.000000   41.965000 -114.596389  2402.000000   7880.000000   

       population_total  area_total_sq_mi  area_land_sq_mi  area_water_sq_mi  \
count      4.820000e+02        480.000000       482.000000        481.000000   
mean       6.489493e+04         18.442183        16.840981          1.589630   
std        2.032041e+05         36.363230        32.694647          9.490386   
min        1.000000e+00          0.314000         0.314000          0.000000   
25%        1.090200e+04          3.708250         3.506500          0.000000   
50%        2.905750e+04          9.093000         8.362000          0.029000   
75%        6.646650e+04         19.878250        19.090000          0.244000   
max        3.884307e+06        503.000000       469.000000        185.020000   

       area_total_km2  area_land_km2  area_water_km2  area_water_percent  \
count      477.000000     478.000000      478.000000          477.000000   
mean        46.753283      43.547021        3.125178            5.301801   
std         90.972269      84.933022       11.562269           14.656428   
min          0.813000       0.813000        0.000000            0.000000   
25%          9.551000       9.025000        0.000250            0.000000   
50%         23.551000      21.533000        0.078500            0.340000   
75%         51.772000      49.322000        0.623250            1.870000   
max       1302.000000    1214.000000      122.270000           84.580000   

       Unnamed: 14  Unnamed: 15  
count          0.0          0.0  
mean           NaN          NaN  
std            NaN          NaN  
min            NaN          NaN  
25%            NaN          NaN  
50%            NaN          NaN  
75%            NaN          NaN  
max            NaN          NaN

In [122]:
# let us try to practice with a real dataset using california city data
# 
datas = pd.read_csv('C:\\Users\\User\\Desktop\\Datasets\\car_scrape4.csv')
datas.head()

title  odometer location    isimported          engine  \
0         Toyota Corolla     60127    Lagos  Locally used  4-cylinder(I4)   
1              Acura MDX    132908    Lagos  Foreign Used  6-cylinder(V6)   
2           Lexus ES 350    120412    Lagos  Locally used  6-cylinder(V6)   
3  Mercedes-Benz GLK 350     67640    Lagos  Foreign Used  4-cylinder(I4)   
4    Mercedes-Benz E 200     92440    Abuja  Foreign Used  4-cylinder(I4)   

  transmission    fuel   paint    price  year  
0    automatic  petrol  Silver  1995000  2009  
1    automatic  petrol  Whine   3315000  2009  
2    automatic  petrol  Silver  2355000  2008  
3    automatic  petrol   Black  9915000  2013  
4    automatic  petrol   Black  9790000  2013

In [127]:
import pandas as pd
mydata = pd.read_excel("C:\\Users\\User\\Desktop\\Datasets\\Blood Transfusion Service Center.xls")
mydata.head()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)  \
0          2.333333                 50                  12500      98.233333   
1          0.066667                 13                   3250      28.300000   
2          0.833333                 16                   4000      35.133333   
3          2.333333                 20                   5000      45.066667   
4          0.533333                 24                   6000      76.833333   

   whether he/she donated \nblood in March 2007  
0                                             1  
1                                             1  
2                                             1  
3                                             1  
4                                             0

In [155]:
import pandas as pd
mydat = pd.read_csv("C:\\Users\\User\\Desktop\\Datasets\\us_births.csv")
mydat.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548