In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
Weather = pd.read_csv('C:\\Users\\User\\Desktop\\Datasets\\BicycleWeather.csv')
Weather.head()

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20120105   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  ...  WT17  WT05  WT02  WT22  \
0     0     0     0   128    50    47   100  ... -9999 -9999 -9999 -9999   
1   109     0     0   106    28    45   180  ... -9999 -9999 -9999 -9999   
2     8     0     0   117    72    23   180  ... -9999 -9999 -9999 -9999   
3   203     0     0   122    56    47   180  ... -9999 -9999 -9999 -9999   
4    13     0     0    89    28    61   200  ... -9999 -9999 -9999 -9999   

   WT04  WT13  WT16  WT08  WT18  WT03  
0 -9999 -9999 -9999 -9999 -9999 -9999  
1 -9999     1     1 -9999 -9999 -9999  
2 -9999 -9999     1 -9999 -9999 -9999  
3 -9999     1     1 -9999 -9999 -9999  
4 -9999 -9999     1 -9999 -9999 -9999  

[5 rows x 26 columns]

In [6]:
P = Weather['PRCP'].values
print("PRCP\n",P,"\n")



PRCP
 [  0 109   8 ... 102   0  58] 



In [7]:
inches = P/254 
inches.shape

(1340,)

In [8]:
inches
val = pd.notna(inches)
inches[val]

array([0.        , 0.42913386, 0.03149606, ..., 0.4015748 , 0.        ,
       0.22834646])

In [9]:
inche =inches[val]
non_zero = (inche > 0)
inche[non_zero]

array([0.42913386, 0.03149606, 0.7992126 , 0.0511811 , 0.0984252 ,
       0.16929134, 0.03937008, 0.16141732, 0.20866142, 0.0984252 ,
       0.31889764, 0.77952756, 0.5984252 , 0.53149606, 0.11811024,
       0.24015748, 0.33858268, 0.31889764, 0.18897638, 1.09055118,
       0.14173228, 0.07086614, 0.53149606, 0.01181102, 0.11023622,
       0.0984252 , 0.0984252 , 0.03149606, 0.03937008, 0.4488189 ,
       0.0984252 , 0.07086614, 0.68110236, 0.2519685 , 0.11811024,
       0.03149606, 0.33858268, 0.4488189 , 0.0511811 , 0.14173228,
       0.03149606, 0.07874016, 0.27165354, 0.01968504, 0.14173228,
       0.40944882, 0.53937008, 0.75984252, 0.37007874, 0.33858268,
       0.94094488, 0.33070866, 0.37007874, 0.14173228, 0.07874016,
       0.14173228, 0.0511811 , 0.16141732, 0.18897638, 0.0511811 ,
       1.07874016, 0.22047244, 0.51968504, 0.05905512, 0.05905512,
       0.18110236, 0.01181102, 0.09055118, 0.01968504, 0.31889764,
       0.07086614, 0.07086614, 0.42913386, 0.25984252, 0.16929

In [10]:
inche =inches[val]
zeros = (inche == 0)
inche[zeros]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [11]:
(inche[non_zero]) * 100 / 250

array([0.17165354, 0.01259843, 0.31968504, 0.02047244, 0.03937008,
       0.06771654, 0.01574803, 0.06456693, 0.08346457, 0.03937008,
       0.12755906, 0.31181102, 0.23937008, 0.21259843, 0.04724409,
       0.09606299, 0.13543307, 0.12755906, 0.07559055, 0.43622047,
       0.05669291, 0.02834646, 0.21259843, 0.00472441, 0.04409449,
       0.03937008, 0.03937008, 0.01259843, 0.01574803, 0.17952756,
       0.03937008, 0.02834646, 0.27244094, 0.1007874 , 0.04724409,
       0.01259843, 0.13543307, 0.17952756, 0.02047244, 0.05669291,
       0.01259843, 0.03149606, 0.10866142, 0.00787402, 0.05669291,
       0.16377953, 0.21574803, 0.30393701, 0.1480315 , 0.13543307,
       0.37637795, 0.13228346, 0.1480315 , 0.05669291, 0.03149606,
       0.05669291, 0.02047244, 0.06456693, 0.07559055, 0.02047244,
       0.43149606, 0.08818898, 0.20787402, 0.02362205, 0.02362205,
       0.07244094, 0.00472441, 0.03622047, 0.00787402, 0.12755906,
       0.02834646, 0.02834646, 0.17165354, 0.10393701, 0.06771

In [12]:
print("Median precip on rainy days in BicycleWeather: ", np.median(inche[non_zero]))
print("Median precip on summer days in BicycleWeather: ", np.median(inche[zeros]))
print("Maximum precip on summer days in BicycleWeather: ", np.max(inche[zeros]))
print("Median precip on non-summer rainy days BicycleWeather: ", np.median(inche[non_zero & ~zeros]))

Median precip on rainy days in BicycleWeather:  0.14960629921259844
Median precip on summer days in BicycleWeather:  0.0
Maximum precip on summer days in BicycleWeather:  0.0
Median precip on non-summer rainy days BicycleWeather:  0.14960629921259844
