In [2]:
import numpy as np

In [2]:
 d=np.arange(50)
 d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
a=np.random.random((4,5))
a

array([[0.3325142 , 0.47174471, 0.59731239, 0.81646976, 0.11136327],
       [0.05558285, 0.61302955, 0.80193551, 0.93034575, 0.11892005],
       [0.22352014, 0.08630487, 0.78193395, 0.71919229, 0.31734097],
       [0.84994316, 0.9806075 , 0.30688666, 0.57672572, 0.51151547]])

In [4]:
a.ndim

2

In [5]:
first, second,third = np.vsplit(a, [2,4])
print("the first split\n",first)
print("the second split\n",second)
print("the third split\n",third)

the first split
 [[0.3325142  0.47174471 0.59731239 0.81646976 0.11136327]
 [0.05558285 0.61302955 0.80193551 0.93034575 0.11892005]]
the second split
 [[0.22352014 0.08630487 0.78193395 0.71919229 0.31734097]
 [0.84994316 0.9806075  0.30688666 0.57672572 0.51151547]]
the third split
 []


In [6]:
x1, x2, x3 = np.split(d, (15,30))
print(x1,x2,x3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[17,19,20,21,22]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [17, 19, 20, 21, 22]])

In [14]:
np.random.randint(0,1,(4,5) )

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
import pandas as pd
us_births=pd.read_csv('C:\\Users\\User\\Desktop\\Datasets\\us_births.csv')
us_births.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [11]:
yr = np.array(us_births['year'])
gen = np.array(us_births['gender'])
br = np.array(us_births['births'])
print("YEARS\n",yr,"\n")
print("GENDERS\n",gen)
print("BIRTHS\n",br)

YEARS
 [1969 1969 1969 ... 2008 2008 2008] 

GENDERS
 ['F' 'M' 'F' ... 'M' 'F' 'M']
BIRTHS
 [  4046   4440   4454 ... 165468 173215 181235]


In [18]:
print("us total births sum: ", np.sum(br))
print("us total births mean: ", np.mean(br))
print("us total births median: ", np.median(br))

us total births sum:  151774378
us total births mean:  9762.293561458802
us total births median:  4814.0


In [22]:
y= br[1::2].sum()
x= br[0::2].sum()
      
print('aggregation of sum of female birth:',  x)

print('aggregation of sum of Male birth:',  y)


aggregation of sum of female birth: 76768938
aggregation of sum of Male birth: 75005440


In [24]:
print("minimum births:   ", br.argmin())
print("maximum births:   ", br.argmax())

minimum births:    4715
maximum births:    15514


In [25]:

a = gen[br.argmax()]
b = gen[br.argmin()]
print("gender with maximum birth\n",a)
print("gender with minimum birth\n", b)

gender with maximum birth
 M
gender with minimum birth
 F


In [26]:
c = yr[br.argmax()]
d = yr[br.argmin()]
print("year with maximum birth\n",c)
print("year with minimum birth\n", d)

year with maximum birth
 2007
year with minimum birth
 1975
