#here we go

In [1]:
import numpy as np
np.__version__

'1.19.2'

In [2]:
np.sum?

In [3]:
 g=['1',2,3,'4',False,5,'6',7,8,9]
print(g)

['1', 2, 3, '4', False, 5, '6', 7, 8, 9]


In [4]:
type(g)

list

In [6]:
type(g[4])

bool

In [7]:
[type(e) for e in g]

[str, int, int, str, bool, int, str, int, int, int]

In [8]:
%timeit g

38.6 ns ± 1.91 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [9]:
import array
ft=array.array('i',list(range(1, 10)))
ft

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(15,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype=float)   

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [13]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [15]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [16]:
np.random.random((3,2))

array([[0.23405369, 0.27511352],
       [0.60479951, 0.20478195],
       [0.38118911, 0.32029908]])

In [17]:
np.random.normal(0,1,(3,3))

array([[-1.65712623,  2.23337469, -0.338441  ],
       [ 1.40853248, -0.713257  , -0.36030338],
       [ 1.77542221, -0.06063977, -0.88323188]])

In [18]:
np.random.randint(0,6)

2

In [19]:
np.random.randint(100,5000)

862

In [20]:
np.random.randint(0,9,(3,5))

array([[6, 1, 8, 2, 6],
       [7, 4, 0, 3, 0],
       [3, 8, 7, 3, 5]])

In [5]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [23]:
hy=np.random.RandomState(3)
x=hy.randint(8, size=4)
x

array([2, 0, 1, 3])

In [24]:
x1=np.array([1,4,6,7,8,9])

In [25]:
np.random.normal(3,9,(3,3))

array([[ 12.46255575,  -5.79882099,   7.93253412],
       [-17.79391815,   8.54461374,  -5.6706915 ],
       [ 16.58329545,  12.26255788,   5.75644521]])

In [26]:
x4=np.random.randint(15,size=(3,4,5))
x4

array([[[ 6, 11, 10,  2,  8],
        [ 3, 10, 14,  9,  6],
        [14, 12,  0,  3,  8],
        [12,  6, 10,  1, 12]],

       [[ 9,  9,  1, 10,  2],
        [12,  5,  5,  6,  6],
        [ 8,  2,  2, 13, 10],
        [13, 11, 11, 12,  2]],

       [[12,  7,  6,  2,  8],
        [13,  2, 10,  5,  2],
        [ 0, 12,  1,  5,  4],
        [ 8,  2,  7,  8,  6]]])

In [27]:
x4.size

60

In [28]:
x4.shape

(3, 4, 5)

In [29]:
x4.dtype

dtype('int32')

In [30]:
x4.itemsize

4

In [31]:
x4.nbytes

240

x5=np.array(['yes','september','8','hi','me'])
x5

In [32]:
x4.nbytes

240

In [33]:
x1

array([1, 4, 6, 7, 8, 9])

In [34]:
x1[-1]

9

In [35]:
x1[3]

7

In [36]:
x1[1]=4
x1

array([1, 4, 6, 7, 8, 9])

In [37]:
x4

array([[[ 6, 11, 10,  2,  8],
        [ 3, 10, 14,  9,  6],
        [14, 12,  0,  3,  8],
        [12,  6, 10,  1, 12]],

       [[ 9,  9,  1, 10,  2],
        [12,  5,  5,  6,  6],
        [ 8,  2,  2, 13, 10],
        [13, 11, 11, 12,  2]],

       [[12,  7,  6,  2,  8],
        [13,  2, 10,  5,  2],
        [ 0, 12,  1,  5,  4],
        [ 8,  2,  7,  8,  6]]])

In [38]:
x4[1,2]

array([ 8,  2,  2, 13, 10])

In [39]:
x4[1,-2,]=100
x4

array([[[  6,  11,  10,   2,   8],
        [  3,  10,  14,   9,   6],
        [ 14,  12,   0,   3,   8],
        [ 12,   6,  10,   1,  12]],

       [[  9,   9,   1,  10,   2],
        [ 12,   5,   5,   6,   6],
        [100, 100, 100, 100, 100],
        [ 13,  11,  11,  12,   2]],

       [[ 12,   7,   6,   2,   8],
        [ 13,   2,  10,   5,   2],
        [  0,  12,   1,   5,   4],
        [  8,   2,   7,   8,   6]]])

In [40]:
tri = np.linspace(0, np.pi,5)
tri

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [41]:
expo = [1,2,3]
np.exp(expo)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [42]:
d=([1,2,3,4,5])
d

[1, 2, 3, 4, 5]

In [43]:
  np.max(d)                                                           

5

In [44]:
np.min(d)

1

In [45]:
import pandas as pd
president_height=pd.read_csv('C:\\Users\\User\\Desktop\\Datasets\\president_height.csv')
president_height.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [7]:
import pandas as pd
us_birth = pd.read_csv('C:\\Users\\User\\Desktop\\\Datasets\\Us_births.csv')
us_birth.head()

year  month  day gender  births
0  1969      1  1.0      F    4046
1  1969      1  1.0      M    4440
2  1969      1  2.0      F    4454
3  1969      1  2.0      M    4548
4  1969      1  3.0      F    4548

In [11]:
# We need to extract each columns of the table and convert it to np array so we can compute np aggregation on it.
birth = np.array(us_birth['births'])
gen_birth = np.array(us_birth['gender'])
# print("president height\n",pres_height,"\n")
# print("president names\n",pres_name)
birth
gen_birth

array(['F', 'M', 'F', ..., 'M', 'F', 'M'], dtype=object)