In [1]:
import numpy as np
import pandas as pd

In [2]:
# create series array
record=pd.Series([1,2,3,4,5,6,7,8])
record

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [3]:
#to see only the values of the series
record.values

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [4]:
#to see only the index of the series
record.index

RangeIndex(start=0, stop=8, step=1)

In [5]:
#we can get each element of the series by index
record[6]

7

In [6]:
record[2:5]

2    3
3    4
4    5
dtype: int64

In [7]:
record[-5:]

3    4
4    5
5    6
6    7
7    8
dtype: int64

In [8]:
record[-6:-1]

2    3
3    4
4    5
5    6
6    7
dtype: int64

In [9]:
record2=pd.Series([23,24,25,26,27],index=['a','b','c','d','e'])
record2

a    23
b    24
c    25
d    26
e    27
dtype: int64

In [10]:
record2['a':'d']

a    23
b    24
c    25
d    26
dtype: int64

In [11]:
#from a specialized dictionary
states={'Oyo':250000,'Lagos':676655,'Kano':678987,'Kaduna':567898,'Imo':4345667,'Enugu':789089}
statesdata=pd.Series(states)
statesdata

Oyo        250000
Lagos      676655
Kano       678987
Kaduna     567898
Imo       4345667
Enugu      789089
dtype: int64

In [12]:
statesdata['Lagos']

676655

In [13]:
statesdata['Oyo':'Imo']

Oyo        250000
Lagos      676655
Kano       678987
Kaduna     567898
Imo       4345667
dtype: int64

In [14]:
census=pd.DataFrame({'Population':statesdata})
census

Population
Oyo         250000
Lagos       676655
Kano        678987
Kaduna      567898
Imo        4345667
Enugu       789089

In [15]:
pop_census=pd.DataFrame({'Population':statesdata,'landmass':statesdata})
pop_census

Population  landmass
Oyo         250000    250000
Lagos       676655    676655
Kano        678987    678987
Kaduna      567898    567898
Imo        4345667   4345667
Enugu       789089    789089

In [16]:
#lists out the columns on the table
pop_census.columns

Index(['Population', 'landmass'], dtype='object')

In [17]:
#list out all the valuesof the dataframe
pop_census.values

array([[ 250000,  250000],
       [ 676655,  676655],
       [ 678987,  678987],
       [ 567898,  567898],
       [4345667, 4345667],
       [ 789089,  789089]], dtype=int64)

In [18]:
#lists out all the indexes
pop_census.index

Index(['Oyo', 'Lagos', 'Kano', 'Kaduna', 'Imo', 'Enugu'], dtype='object')

In [19]:
#indexing a dataframe through its column name
pop_census['landmass']

Oyo        250000
Lagos      676655
Kano       678987
Kaduna     567898
Imo       4345667
Enugu      789089
Name: landmass, dtype: int64

In [20]:
#get the population of Imo using index
pop_census['Population']['Imo']

4345667

In [21]:
pop_census['Oyo':'Imo']

Population  landmass
Oyo         250000    250000
Lagos       676655    676655
Kano        678987    678987
Kaduna      567898    567898
Imo        4345667   4345667

In [22]:
student=pd.Series(['Sunday','Jude','Charles','Rose','Michael'])
student

0     Sunday
1       Jude
2    Charles
3       Rose
4    Michael
dtype: object

In [23]:
studentrec=pd.DataFrame(student,columns=['Name'], index=[0,1,2,3,4])
studentrec

Name
0   Sunday
1     Jude
2  Charles
3     Rose
4  Michael

In [24]:
list1=np.array([1,2,3,4,5,6,7,8,9])
list1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
fancy=[0,5,6,8]
list1[fancy]

array([1, 6, 7, 9])

In [26]:
ind=pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [27]:
ind[2]

5

In [28]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [29]:
indA=pd.Index([1,3,5,7,9])
indB=pd.Index([2,3,5,7,11])

In [30]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [31]:
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [32]:
df=pd.DataFrame(rng.randint(0,10,(3,4)),columns=['a','b','c','d'])
df

a  b  c  d
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [33]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [34]:
np.sin(df*np.pi/4)

a             b         c             d
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [35]:
np.sin(pop_census*np.pi/4)

Population      landmass
Oyo    -1.394945e-11 -1.394945e-11
Lagos  -7.071068e-01 -7.071068e-01
Kano    7.071068e-01  7.071068e-01
Kaduna  1.000000e+00  1.000000e+00
Imo     7.071068e-01  7.071068e-01
Enugu   7.071068e-01  7.071068e-01

In [36]:
data=pd.read_csv('C:\\Users\\User\\Downloads\\Datasets\\california_cities.csv')
data.head()

Unnamed: 0         city       latd       longd  elevation_m  elevation_ft  \
0           0     Adelanto  34.576111 -117.432778        875.0        2871.0   
1           1  AgouraHills  34.153333 -118.761667        281.0         922.0   
2           2      Alameda  37.756111 -122.274444          NaN          33.0   
3           3       Albany  37.886944 -122.297778          NaN          43.0   
4           4     Alhambra  34.081944 -118.135000        150.0         492.0   

   population_total  area_total_sq_mi  area_land_sq_mi  area_water_sq_mi  \
0             31765            56.027           56.009             0.018   
1             20330             7.822            7.793             0.029   
2             75467            22.960           10.611            12.349   
3             18969             5.465            1.788             3.677   
4             83089             7.632            7.631             0.001   

   area_total_km2  area_land_km2  area_water_km2  area_water_percent  \
0         145.107        145.062           0.046                0.03   
1          20.260         20.184           0.076                0.37   
2          59.465         27.482          31.983               53.79   
3          14.155          4.632           9.524               67.28   
4          19.766         19.763           0.003                0.01   

   Unnamed: 14  Unnamed: 15  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN

In [37]:
data.describe()

Unnamed: 0        latd       longd  elevation_m  elevation_ft  \
count  482.000000  482.000000  482.000000   434.000000    470.000000   
mean   240.500000   36.095088 -119.837714   180.416705    567.168723   
std    139.285678    2.298006    2.147676   309.531825   1001.265722   
min      0.000000   32.578333 -124.263333   -34.000000   -180.000000   
25%    120.250000   33.977292 -121.954931    22.000000     69.000000   
50%    240.500000   36.204722 -119.708611    67.000000    200.000000   
75%    360.750000   37.886667 -117.977292   173.500000    515.000000   
max    481.000000   41.965000 -114.596389  2402.000000   7880.000000   

       population_total  area_total_sq_mi  area_land_sq_mi  area_water_sq_mi  \
count      4.820000e+02        480.000000       482.000000        481.000000   
mean       6.489493e+04         18.442183        16.840981          1.589630   
std        2.032041e+05         36.363230        32.694647          9.490386   
min        1.000000e+00          0.314000         0.314000          0.000000   
25%        1.090200e+04          3.708250         3.506500          0.000000   
50%        2.905750e+04          9.093000         8.362000          0.029000   
75%        6.646650e+04         19.878250        19.090000          0.244000   
max        3.884307e+06        503.000000       469.000000        185.020000   

       area_total_km2  area_land_km2  area_water_km2  area_water_percent  \
count      477.000000     478.000000      478.000000          477.000000   
mean        46.753283      43.547021        3.125178            5.301801   
std         90.972269      84.933022       11.562269           14.656428   
min          0.813000       0.813000        0.000000            0.000000   
25%          9.551000       9.025000        0.000250            0.000000   
50%         23.551000      21.533000        0.078500            0.340000   
75%         51.772000      49.322000        0.623250            1.870000   
max       1302.000000    1214.000000      122.270000           84.580000   

       Unnamed: 14  Unnamed: 15  
count          0.0          0.0  
mean           NaN          NaN  
std            NaN          NaN  
min            NaN          NaN  
25%            NaN          NaN  
50%            NaN          NaN  
75%            NaN          NaN  
max            NaN          NaN

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          482 non-null    int64  
 1   city                482 non-null    object 
 2   latd                482 non-null    float64
 3   longd               482 non-null    float64
 4   elevation_m         434 non-null    float64
 5   elevation_ft        470 non-null    float64
 6   population_total    482 non-null    int64  
 7   area_total_sq_mi    480 non-null    float64
 8   area_land_sq_mi     482 non-null    float64
 9   area_water_sq_mi    481 non-null    float64
 10  area_total_km2      477 non-null    float64
 11  area_land_km2       478 non-null    float64
 12  area_water_km2      478 non-null    float64
 13  area_water_percent  477 non-null    float64
 14  Unnamed: 14         0 non-null      float64
 15  Unnamed: 15         0 non-null      float64
dtypes: float

In [39]:
data['latd'].mean(),data['latd'].std()

(36.09508808165976, 2.298005905096742)

In [40]:
  data.shape,data.ndim,data.size

((482, 16), 2, 7712)

In [41]:
data.values

array([[0, 'Adelanto', 34.57611111, ..., 0.03, nan, nan],
       [1, 'AgouraHills', 34.15333333, ..., 0.37, nan, nan],
       [2, 'Alameda', 37.75611111, ..., 53.79, nan, nan],
       ...,
       [479, 'YubaCity', 39.13472222, ..., 0.53, nan, nan],
       [480, 'Yucaipa', 34.03027778, ..., 0.02, nan, nan],
       [481, 'YuccaValley', 34.13333333, ..., 0.0, nan, nan]],
      dtype=object)

In [42]:
data.index

RangeIndex(start=0, stop=482, step=1)

In [43]:
data['density']=data['population_total']/data['area_total_sq_mi']
data.head()

Unnamed: 0         city       latd       longd  elevation_m  elevation_ft  \
0           0     Adelanto  34.576111 -117.432778        875.0        2871.0   
1           1  AgouraHills  34.153333 -118.761667        281.0         922.0   
2           2      Alameda  37.756111 -122.274444          NaN          33.0   
3           3       Albany  37.886944 -122.297778          NaN          43.0   
4           4     Alhambra  34.081944 -118.135000        150.0         492.0   

   population_total  area_total_sq_mi  area_land_sq_mi  area_water_sq_mi  \
0             31765            56.027           56.009             0.018   
1             20330             7.822            7.793             0.029   
2             75467            22.960           10.611            12.349   
3             18969             5.465            1.788             3.677   
4             83089             7.632            7.631             0.001   

   area_total_km2  area_land_km2  area_water_km2  area_water_percent  \
0         145.107        145.062           0.046                0.03   
1          20.260         20.184           0.076                0.37   
2          59.465         27.482          31.983               53.79   
3          14.155          4.632           9.524               67.28   
4          19.766         19.763           0.003                0.01   

   Unnamed: 14  Unnamed: 15       density  
0          NaN          NaN    566.958788  
1          NaN          NaN   2599.079519  
2          NaN          NaN   3286.890244  
3          NaN          NaN   3470.997255  
4          NaN          NaN  10886.923480

In [44]:
data.columns

Index(['Unnamed: 0', 'city', 'latd', 'longd', 'elevation_m', 'elevation_ft',
       'population_total', 'area_total_sq_mi', 'area_land_sq_mi',
       'area_water_sq_mi', 'area_total_km2', 'area_land_km2', 'area_water_km2',
       'area_water_percent', 'Unnamed: 14', 'Unnamed: 15', 'density'],
      dtype='object')

In [45]:
change_column=np.array(data.columns)
change_column[0]='S/N'
change_column

array(['S/N', 'city', 'latd', 'longd', 'elevation_m', 'elevation_ft',
       'population_total', 'area_total_sq_mi', 'area_land_sq_mi',
       'area_water_sq_mi', 'area_total_km2', 'area_land_km2',
       'area_water_km2', 'area_water_percent', 'Unnamed: 14',
       'Unnamed: 15', 'density'], dtype=object)

In [46]:
data=pd.DataFrame(data.values,columns=change_column)
data.head()

S/N         city     latd    longd elevation_m elevation_ft  \
0   0     Adelanto  34.5761 -117.433         875         2871   
1   1  AgouraHills  34.1533 -118.762         281          922   
2   2      Alameda  37.7561 -122.274         NaN           33   
3   3       Albany  37.8869 -122.298         NaN           43   
4   4     Alhambra  34.0819 -118.135         150          492   

  population_total area_total_sq_mi area_land_sq_mi area_water_sq_mi  \
0            31765           56.027          56.009            0.018   
1            20330            7.822           7.793            0.029   
2            75467            22.96          10.611           12.349   
3            18969            5.465           1.788            3.677   
4            83089            7.632           7.631            0.001   

  area_total_km2 area_land_km2 area_water_km2 area_water_percent Unnamed: 14  \
0        145.107       145.062          0.046               0.03         NaN   
1          20.26        20.184          0.076               0.37         NaN   
2         59.465        27.482         31.983              53.79         NaN   
3         14.155         4.632          9.524              67.28         NaN   
4         19.766        19.763          0.003               0.01         NaN   

  Unnamed: 15  density  
0         NaN  566.959  
1         NaN  2599.08  
2         NaN  3286.89  
3         NaN     3471  
4         NaN  10886.9

In [47]:
data.drop(['Unnamed: 14','Unnamed: 15'], axis=1).head()

S/N         city     latd    longd elevation_m elevation_ft  \
0   0     Adelanto  34.5761 -117.433         875         2871   
1   1  AgouraHills  34.1533 -118.762         281          922   
2   2      Alameda  37.7561 -122.274         NaN           33   
3   3       Albany  37.8869 -122.298         NaN           43   
4   4     Alhambra  34.0819 -118.135         150          492   

  population_total area_total_sq_mi area_land_sq_mi area_water_sq_mi  \
0            31765           56.027          56.009            0.018   
1            20330            7.822           7.793            0.029   
2            75467            22.96          10.611           12.349   
3            18969            5.465           1.788            3.677   
4            83089            7.632           7.631            0.001   

  area_total_km2 area_land_km2 area_water_km2 area_water_percent  density  
0        145.107       145.062          0.046               0.03  566.959  
1          20.26        20.184          0.076               0.37  2599.08  
2         59.465        27.482         31.983              53.79  3286.89  
3         14.155         4.632          9.524              67.28     3471  
4         19.766        19.763          0.003               0.01  10886.9

In [48]:
data.city

0         Adelanto
1      AgouraHills
2          Alameda
3           Albany
4         Alhambra
          ...     
477     Yountville
478          Yreka
479       YubaCity
480        Yucaipa
481    YuccaValley
Name: city, Length: 482, dtype: object

In [49]:
data.density

0      566.959
1      2599.08
2      3286.89
3         3471
4      10886.9
        ...   
477    1915.74
478    772.406
479    4429.93
480    1841.57
481    517.306
Name: density, Length: 482, dtype: object

In [50]:
data.latd

0      34.5761
1      34.1533
2      37.7561
3      37.8869
4      34.0819
        ...   
477    38.4031
478    41.7267
479    39.1347
480    34.0303
481    34.1333
Name: latd, Length: 482, dtype: object

In [51]:
data.population_total.sum()

31279358

In [52]:
ser1=pd.Series([2,4,6], index=[0,1,2])
ser2=pd.Series([1,3,5], index=[1,2,3])
print(ser1)
print(ser2)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64


In [53]:
ser1+ser2

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [54]:
ser1.add(ser2, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [55]:
x=np.array([1,2,None,3,4,5,6])
x

array([1, 2, None, 3, 4, 5, 6], dtype=object)